### PR TITLE
Python optimizations

### PR DESCRIPTION
**Pull request by QuLogic**
By writing NumPy code more idiomatically, this produces at least twice the speed. Probably it would be even faster if we could get rid of that `ibool` indirection somehow.

### CODE REVIEW

**Comment by komatits** [comment]
Hi,

let us keep ibool; the goal of the 1D code is not to be fast but to be 
very close to the structure of the 2D and 3D codes, so that people can 
learn how the method and the 2D and 3D codes work.

Thanks,
Dimitri.

On 01/14/2015 08:56 AM, Elliott Sales de Andrade wrote:
> By writing NumPy code more idiomatically, this produces at least twice
> the speed. Probably it would be even faster if we could get rid of that
> |ibool| indirection somehow.
>
> ------------------------------------------------------------------------
>
>
>         You can merge this Pull Request by running
>
>    git pull https://github.com/QuLogic/specfem1d python-optimize
>
> Or view, comment on, or merge it at:
>
> https://github.com/geodynamics/specfem1d/pull/21
>
>
>         Commit Summary
>
>   * py: Change dtype of ibool to integer.
>   * py: Simplify grid plotting.
>   * py: Simplify stiffness matrix creation.
>   * py: Simplify mass matrix creation slightly.
>   * py: Simplify homogeneous grid creation a bit.
>   * py: Simplify Jacobian calculation.
>   * py: Simplify GLJ derivative calculation.
>   * py: Simplify Lagrange derivatives a bit.
>   * py: Tweak main program a bit.
>
>
>         File Changes
>
>   * *M* Python_version/config.py
>     <https://github.com/geodynamics/specfem1d/pull/21/files#diff-0> (2)
>   * *M* Python_version/functions.py
>     <https://github.com/geodynamics/specfem1d/pull/21/files#diff-1> (71)
>   * *M* Python_version/gll.py
>     <https://github.com/geodynamics/specfem1d/pull/21/files#diff-2> (135)
>   * *M* Python_version/grid.py
>     <https://github.com/geodynamics/specfem1d/pull/21/files#diff-3> (70)
>   * *M* Python_version/specfem1d.py
>     <https://github.com/geodynamics/specfem1d/pull/21/files#diff-4> (25)
>
>
>         Patch Links:
>
>   * https://github.com/geodynamics/specfem1d/pull/21.patch
>   * https://github.com/geodynamics/specfem1d/pull/21.diff
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/geodynamics/specfem1d/pull/21>.
>

-- 
Dimitri Komatitsch
CNRS Research Director (DR CNRS), Laboratory of Mechanics and Acoustics,
UPR 7051, Marseille, France    http://komatitsch.free.fr

**Comment by QuLogic** [comment]
I did not remove `ibool`; I assume it might require an algorithmic change (or some sort of adjustment at least) and I'm not really trying to do that. This is just optimization using a more idiomatic code style.

**Comment by eheien** [comment]
Should I go ahead and merge these changes?

**Comment by komatits** [comment]
Yes!


On 01/14/2015 06:24 PM, Eric Heien wrote:
> Should I go ahead and merge these changes?
>
>  > On Jan 14, 2015, at 12:58 AM, Elliott Sales de Andrade
> <notifications@github.com> wrote:
>  >
>  > I did not remove ibool; I assume it might require an algorithmic
> change (or some sort of adjustment at least) and I'm not really trying
> to do that. This is just optimization using a more idiomatic code style.
>  >
>  > —
>  > Reply to this email directly or view it on GitHub.
>  >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/geodynamics/specfem1d/pull/21#issuecomment-69954147>.
>

-- 
Dimitri Komatitsch
CNRS Research Director (DR CNRS), Laboratory of Mechanics and Acoustics,
UPR 7051, Marseille, France    http://komatitsch.free.fr

**Pull request merged**
