### PR TITLE
Updated makefiles

### PR DESCRIPTION
**Pull request by QuLogic**
There were some missing directories and manual fiddling with directories in the Makefiles. It's easier to just have the `.gitignore` placeholder instead.

Also, re-write the Makefiles so that they are similar to the 2D, 3D, etc. cases where the rules are pattern-based.

### CODE REVIEW

**Comment by QuLogic** [comment]
PS, @eheien Is `devel` actually used here? It's actually _behind_ `master`.

**Comment by komatits** [comment]
Hi all,

For the particular case of the 1D code I would suggest merging devel 
into master once and for all and then permanently removing devel and 
keeping master only

(the Git page http://geodynamics.org/cig/software/specfem1d/ does not 
even mention it, thus nobody knows it is there)

PS (unrelated): on the Git page the "Jenkins Testing" part seems broken.

Thanks,
Dimitri.

On 01/06/2015 08:03 AM, Elliott Sales de Andrade wrote:
> PS, @eheien <https://github.com/eheien> Is |devel| actually used here?
> It's actually /behind/ |master|.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/geodynamics/specfem1d/pull/14#issuecomment-68833197>.
>

-- 
Dimitri Komatitsch
CNRS Research Director (DR CNRS), Laboratory of Mechanics and Acoustics,
UPR 7051, Marseille, France    http://komatitsch.free.fr

**Comment by eheien** [comment]
I deleted the devel branch in specfem1d.  Where exactly is the broken Jenkins Testing section?  The only Jenkins status I know of is on the CIG software page (http://geodynamics.org/cig/software/specfem1d/) which seems to work fine.

Thanks,

-Eric

**Comment by komatits** [comment]
Thanks!

Regarding the Jenkins Testing section on my machine when I go to 
http://geodynamics.org/cig/software/specfem1d/ the squares inside the 
table are empty / broken (they try to display 
http://blofeld.geodynamics.org:8080/job/specfem1d/label=goldfinger.geodynamics.org 
  but nothing happens).

If they work on your machine could it be a firewall problem?

thanks,
Dimitri.

On 01/06/2015 05:48 PM, Eric Heien wrote:
> I deleted the devel branch in specfem1d. Where exactly is the broken
> Jenkins Testing section? The only Jenkins status I know of is on the CIG
> software page (http://geodynamics.org/cig/software/specfem1d/) which
> seems to work fine.
>
> Thanks,
>
> -Eric
>
>  > On Jan 6, 2015, at 4:36 AM, Dimitri Komatitsch
> <notifications@github.com> wrote:
>  >
>  >
>  > Hi all,
>  >
>  > For the particular case of the 1D code I would suggest merging devel
>  > into master once and for all and then permanently removing devel and
>  > keeping master only
>  >
>  > (the Git page http://geodynamics.org/cig/software/specfem1d/ does not
>  > even mention it, thus nobody knows it is there)
>  >
>  > PS (unrelated): on the Git page the "Jenkins Testing" part seems broken.
>  >
>  > Thanks,
>  > Dimitri.
>  >
>  > On 01/06/2015 08:03 AM, Elliott Sales de Andrade wrote:
>  > > PS, @eheien <https://github.com/eheien> Is |devel| actually used here?
>  > > It's actually /behind/ |master|.
>  > >
>  > > —
>  > > Reply to this email directly or view it on GitHub
>  > >
> <https://github.com/geodynamics/specfem1d/pull/14#issuecomment-68833197>.
>  > >
>  >
>  > --
>  > Dimitri Komatitsch
>  > CNRS Research Director (DR CNRS), Laboratory of Mechanics and Acoustics,
>  > UPR 7051, Marseille, France http://komatitsch.free.fr
>  > —
>  > Reply to this email directly or view it on GitHub.
>  >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/geodynamics/specfem1d/pull/14#issuecomment-68892274>.
>

-- 
Dimitri Komatitsch
CNRS Research Director (DR CNRS), Laboratory of Mechanics and Acoustics,
UPR 7051, Marseille, France    http://komatitsch.free.fr

**Comment by QuLogic** [comment]
@eheien That's great; would we be able to add testing of the old Fortran and new Python versions in addition to the new Fortran version?

**Comment by eheien** [comment]
Hi Dimitri,

It works fine on all the machines we tested here, so it might be a case of your firewall blocking access to port 8080.  If you’re not able to access the Jenkins site either (http://blofeld.geodynamics.org:8080) I’m guessing a firewall between you and the server is the cause.

-Eric

**Comment by komatits** [comment]
Hi Eric,

Thanks a lot. It works fine again on my machine, I was connected through 
a public Wireless connection when I tried and noticed the problem, here 
from my office and also from home everything is fine.
Thus it was a firewall problem.

Thanks,
Dimitri.

On 01/07/2015 09:12 PM, Eric Heien wrote:
> Hi Dimitri,
>
> It works fine on all the machines we tested here, so it might be a case
> of your firewall blocking access to port 8080. If you’re not able to
> access the Jenkins site either (http://blofeld.geodynamics.org:8080) I’m
> guessing a firewall between you and the server is the cause.
>
> -Eric
>
>  > On Jan 6, 2015, at 1:18 PM, Dimitri Komatitsch
> <notifications@github.com> wrote:
>  >
>  >
>  > Thanks!
>  >
>  > Regarding the Jenkins Testing section on my machine when I go to
>  > http://geodynamics.org/cig/software/specfem1d/ the squares inside the
>  > table are empty / broken (they try to display
>  >
> http://blofeld.geodynamics.org:8080/job/specfem1d/label=goldfinger.geodynamics.org
>
>  > but nothing happens).
>  >
>  > If they work on your machine could it be a firewall problem?
>  >
>  > thanks,
>  > Dimitri.
>  >
>  > On 01/06/2015 05:48 PM, Eric Heien wrote:
>  > > I deleted the devel branch in specfem1d. Where exactly is the broken
>  > > Jenkins Testing section? The only Jenkins status I know of is on
> the CIG
>  > > software page (http://geodynamics.org/cig/software/specfem1d/) which
>  > > seems to work fine.
>  > >
>  > > Thanks,
>  > >
>  > > -Eric
>  > >
>  > > > On Jan 6, 2015, at 4:36 AM, Dimitri Komatitsch
>  > > <notifications@github.com> wrote:
>  > > >
>  > > >
>  > > > Hi all,
>  > > >
>  > > > For the particular case of the 1D code I would suggest merging devel
>  > > > into master once and for all and then permanently removing devel and
>  > > > keeping master only
>  > > >
>  > > > (the Git page http://geodynamics.org/cig/software/specfem1d/ does
> not
>  > > > even mention it, thus nobody knows it is there)
>  > > >
>  > > > PS (unrelated): on the Git page the "Jenkins Testing" part seems
> broken.
>  > > >
>  > > > Thanks,
>  > > > Dimitri.
>  > > >
>  > > > On 01/06/2015 08:03 AM, Elliott Sales de Andrade wrote:
>  > > > > PS, @eheien <https://github.com/eheien> Is |devel| actually
> used here?
>  > > > > It's actually /behind/ |master|.
>  > > > >
>  > > > > —
>  > > > > Reply to this email directly or view it on GitHub
>  > > > >
>  > >
> <https://github.com/geodynamics/specfem1d/pull/14#issuecomment-68833197>.
>  > > > >
>  > > >
>  > > > --
>  > > > Dimitri Komatitsch
>  > > > CNRS Research Director (DR CNRS), Laboratory of Mechanics and
> Acoustics,
>  > > > UPR 7051, Marseille, France http://komatitsch.free.fr
>  > > > —
>  > > > Reply to this email directly or view it on GitHub.
>  > > >
>  > >
>  > > —
>  > > Reply to this email directly or view it on GitHub
>  > >
> <https://github.com/geodynamics/specfem1d/pull/14#issuecomment-68892274>.
>  > >
>  >
>  > --
>  > Dimitri Komatitsch
>  > CNRS Research Director (DR CNRS), Laboratory of Mechanics and Acoustics,
>  > UPR 7051, Marseille, France http://komatitsch.free.fr
>  > —
>  > Reply to this email directly or view it on GitHub.
>  >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/geodynamics/specfem1d/pull/14#issuecomment-69084017>.
>

-- 
Dimitri Komatitsch
CNRS Research Director (DR CNRS), Laboratory of Mechanics and Acoustics,
UPR 7051, Marseille, France    http://komatitsch.free.fr

**Pull request merged**
